  "stages": [
    {
      "name": "Waiting",
      "refId": "1",
      "requisiteStageRefIds": [],
      "type": "wait",
      "waitTime": "{{ var "waitTime" ?: 5 }}",
    },
    {
      "failPipeline": true,
      "judgmentInputs": [],
      "name": "Manual Judgment",
      "notifications": [],
      "refId": "2",
      "requisiteStageRefIds": [
        "1"
      ],
      "type": "manualJudgment"
    }
  ]
